name: Auto update Python dependencies
on:
  schedule:
    # runs weekly at 00:00 on Mondays
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the head commit of the branch
      uses: actions/checkout@v4
      with:
        ref: master

    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip tox
        pip install --upgrade pip
        pip install pipenv

    - name: Run auto dependency update
      uses: mtl1979/dependencies-autoupdate@v1.2.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        pr-branch: "master"
        update-command: "'pipenv update && tox -e py38'"